main:
  params: [event]
  steps:
    - init:
        assign:
          - eventData: ${event.data}
          - studentId: ${eventData.student_id}
          - courseId: ${eventData.course_id}
          - evaluationId: ${eventData.evaluation_id}
          - score: ${eventData.score}
          - timestamp: ${eventData.timestamp}
    
    - log_start:
        call: sys.log
        args:
          text: '${studentId}'
          severity: INFO
    
    - validate_rule:
        try:
          call: http.post
          args:
            url: VALIDATE_RULE_URL_PLACEHOLDER
            auth:
              type: OIDC
            body:
              student_id: ${studentId}
              course_id: ${courseId}
              evaluation_id: ${evaluationId}
              score: ${score}
              timestamp: ${timestamp}
          result: validationResult
        except:
          as: e
          steps:
            - return_validation_error:
                return:
                  status: VALIDATION_FAILED
                  error: ${e.message}
                  student_id: ${studentId}
    
    - check_validation:
        switch:
          - condition: ${validationResult.body.is_valid == false}
            steps:
              - return_no_rule:
                  return:
                    status: NO_RULE_MATCHED
                    student_id: ${studentId}
    
    - extract_badge_info:
        assign:
          - badgeTemplateId: ${validationResult.body.badge_template_id}
          - badgeTitle: ${validationResult.body.badge_title}
          - ruleId: ${validationResult.body.rule_id}
    
    - call_acreditta:
        try:
          call: http.post
          args:
            url: CALL_ACREDITTA_URL_PLACEHOLDER
            auth:
              type: OIDC
            body:
              student_id: ${studentId}
              badge_template_id: ${badgeTemplateId}
              badge_title: ${badgeTitle}
              course_id: ${courseId}
              evaluation_id: ${evaluationId}
              score: ${score}
              rule_id: ${ruleId}
          result: acredittaResult
        except:
          as: e
          steps:
            - return_acreditta_error:
                return:
                  status: BADGE_ISSUANCE_FAILED
                  error: ${e.message}
                  student_id: ${studentId}
    
    - extract_badge_result:
        assign:
          - badgeId: ${acredittaResult.body.badge_id}
          - badgeUrl: ${acredittaResult.body.badge_url}
          - issuedAt: ${acredittaResult.body.issued_at}
    
    - update_sis:
        try:
          call: http.post
          args:
            url: UPDATE_SIS_URL_PLACEHOLDER
            auth:
              type: OIDC
            body:
              student_id: ${studentId}
              badge_id: ${badgeId}
              badge_url: ${badgeUrl}
              badge_template_id: ${badgeTemplateId}
              badge_title: ${badgeTitle}
              course_id: ${courseId}
              evaluation_id: ${evaluationId}
              score: ${score}
              rule_id: ${ruleId}
              issued_at: ${issuedAt}
          result: sisResult
        except:
          as: e
          steps:
            - return_sis_error:
                return:
                  status: SIS_UPDATE_FAILED
                  error: ${e.message}
                  student_id: ${studentId}
                  badge_id: ${badgeId}
    
    - return_success:
        return:
          status: SUCCESS
          student_id: ${studentId}
          badge_id: ${badgeId}
          badge_url: ${badgeUrl}
          badge_title: ${badgeTitle}
          issued_at: ${issuedAt}
          sis_updated: ${sisResult.body.updated}
